Repository DEFRA/pafs_core, pull requests merged in 2023-10, with the labels that each got.

#710 Feature/ruby 2729 pafs pso rfcc refactoring
  app/models/pafs_core/area.rb
  app/models/pafs_core/user.rb
  app/services/pafs_core/pso_rfcc_service.rb
  db/migrate/20231002152826_add_rfcc_codes.rb
  lib/pafs_core.rb
  lib/pafs_core/data_migration/add_rfcc_codes.rb
  lib/pafs_core/rfcc_codes.rb
  spec/dummy/db/schema.rb
  spec/factories/areas.rb
  spec/fixtures/areas/areas.csv
  spec/fixtures/areas/faulty_areas_data.csv
  spec/fixtures/test_areas.csv
  spec/lib/pafs_core/data_migration/add_rfcc_codes_spec.rb
  spec/lib/pafs_core/data_migration/update_authorities_spec.rb
  spec/models/pafs_core/area_spec.rb
  spec/services/pafs_core/project_service_spec.rb
Labels: feature

#711 Fixing area factory
  spec/factories/areas.rb
Labels: bug

#712 Fix/previous years
  .rubocop_todo.yml
  Gemfile.lock
  app/helpers/pafs_core/projects_helper.rb
  app/presenters/pafs_core/camc3_presenter.rb
  app/services/pafs_core/program_upload_service.rb
  app/services/pafs_core/remove_previous_years_service.rb
  app/services/pafs_core/spreadsheet/contributors/coerce/financial_year.rb
  app/services/pafs_core/spreadsheet/contributors/export.rb
  app/services/pafs_core/spreadsheet_service.rb
  app/views/pafs_core/projects/steps/coastal_erosion_protection_outcomes_summary.html.erb
  app/views/pafs_core/projects/steps/funding_values.html.erb
  app/views/shared/_contributor_values_form.html.erb
  config/locales/en.yml
  lib/pafs_core/data_migration/remove_previous_years.rb
  lib/tasks/pafs_core_tasks.rake
  spec/helpers/pafs_core/projects_helper_spec.rb
  spec/lib/pafs_core/data_migration/remove_previous_years_spec.rb
  spec/lib/tasks/pafs_core_tasks_spec.rb
  spec/presenters/pafs_core/camc3_presenter_spec.rb
  spec/services/pafs_core/remove_previous_years_service_spec.rb
  spec/steps/pafs_core/flood_protection_outcomes_details_spec.rb
Labels: fix
