Repository DEFRA/pafs_core, pull requests merged in 2023-05, with the labels that each got.

#615 Remove redundant debug statements
  app/services/pafs_core/download/all.rb
Labels: fix

#626 Fix/ruby 2485 pafs unable to unselect my project does not move any properties to a lower flood risk category check box after
  Gemfile.lock
  app/helpers/pafs_core/application_helper.rb
  spec/factories/projects.rb
  spec/lib/pafs_core/mapper/funding_sources_spec.rb
Labels: bug, housekeeping

#628 Adding a hint to earliest start date page
  Gemfile.lock
  app/views/pafs_core/projects/steps/earliest_start_date.html.erb
  config/locales/steps.en.yml
Labels: feature, housekeeping
